# Generated by Django 3.2 on 2021-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docboardmodel',
            name='board_type',
            field=models.CharField(choices=[('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JS'), ('es6', 'ES6'), ('node.js', 'NODE'), ('java', 'JAVA'), ('python', 'PYTHON'), ('sql', 'SQL'), ('react', 'REACT'), ('react-native', 'RN'), ('firebase', 'FIREBASE'), ('graphql', 'GRAPHQL')], max_length=40),
        ),
    ]
